export enum ListingCategory {
	'FURNITURE' = 'FURNITURE',
	'FASHION' = 'FASHION',
	'BOOKS' = 'BOOKS',
	'SEASONAL' = 'SEASONAL',
	'DORM GOODS' = 'DORM GOODS',
	'JEWELRIES' = 'JEWELRIES',
	'ELECTRONIC' = 'ELECTRONIC',
	'INSTRUMENT' = 'INSTRUMENT',
}
